const legacy = require("./legacy");

module.exports = {
  _clipboardGetRoleChoices: legacy._clipboardGetRoleChoices,
  _clipboardGetRoleValue: legacy._clipboardGetRoleValue,
  _clipboardGetCurrentUserRole: legacy._clipboardGetCurrentUserRole,
  _clipboardSettingEnabled: legacy._clipboardSettingEnabled,
  _clipboardGetConfiguredMinimumRole: legacy._clipboardGetConfiguredMinimumRole,
  _clipboardUserMeetsMinimumRole: legacy._clipboardUserMeetsMinimumRole,
  _clipboardCanUseCanvasMedia: legacy._clipboardCanUseCanvasMedia,
  _clipboardCanUseCanvasText: legacy._clipboardCanUseCanvasText,
  _clipboardCanUseChatMedia: legacy._clipboardCanUseChatMedia,
  _clipboardCanUseChatUploadButton: legacy._clipboardCanUseChatUploadButton,
  _clipboardCanUseSceneControls: legacy._clipboardCanUseSceneControls,
  _clipboardCanUseScenePasteTool: legacy._clipboardCanUseScenePasteTool,
  _clipboardCanUseSceneUploadTool: legacy._clipboardCanUseSceneUploadTool,
  _clipboardGetDefaultEmptyCanvasTarget: legacy._clipboardGetDefaultEmptyCanvasTarget,
  _clipboardShouldCreateBackingActors: legacy._clipboardShouldCreateBackingActors,
  _clipboardGetChatMediaDisplayMode: legacy._clipboardGetChatMediaDisplayMode,
  _clipboardGetCanvasTextPasteMode: legacy._clipboardGetCanvasTextPasteMode,
  _clipboardGetScenePastePromptMode: legacy._clipboardGetScenePastePromptMode,
  _clipboardGetSelectedTokenPasteMode: legacy._clipboardGetSelectedTokenPasteMode,
  _clipboardGetUploadPathOrganizationMode: legacy._clipboardGetUploadPathOrganizationMode,
  _clipboardCanCreateTokens: legacy._clipboardCanCreateTokens,
  _clipboardCanCreateTiles: legacy._clipboardCanCreateTiles,
  _clipboardCanReplaceTokens: legacy._clipboardCanReplaceTokens,
  _clipboardCanReplaceTiles: legacy._clipboardCanReplaceTiles,
  _clipboardRefreshSceneControlsUi: legacy._clipboardRefreshSceneControlsUi,
  _clipboardRefreshChatUi: legacy._clipboardRefreshChatUi,
  _clipboardRefreshUiForSettingsChange: legacy._clipboardRefreshUiForSettingsChange,
};
