const CLIPBOARD_IMAGE_MODULE_ID = "foundry-paste-eater";
const CLIPBOARD_IMAGE_LEGACY_MODULE_ID = "clipboard-image";
const CLIPBOARD_IMAGE_TITLE = "Foundry Paste Eater";
const CLIPBOARD_IMAGE_DEFAULT_FOLDER = "pasted_images";
const CLIPBOARD_IMAGE_SOURCE_AUTO = "auto";
const CLIPBOARD_IMAGE_SOURCE_DATA = "data";
const CLIPBOARD_IMAGE_SOURCE_S3 = "s3";
const CLIPBOARD_IMAGE_SOURCE_FORGE = "forgevtt";
const CLIPBOARD_IMAGE_FILE_PICKER = foundry.applications.apps.FilePicker.implementation;
const CLIPBOARD_IMAGE_KEYBOARD_MANAGER = foundry.helpers.interaction.KeyboardManager;
const CLIPBOARD_IMAGE_FORM_APPLICATION = foundry.appv1.api.FormApplication;
const CLIPBOARD_IMAGE_SCENE_CONTROLS = ["tiles", "tokens", "sounds"];
const CLIPBOARD_IMAGE_TOOL_PASTE = "foundry-paste-eater-paste";
const CLIPBOARD_IMAGE_TOOL_UPLOAD = "foundry-paste-eater-upload";
const CLIPBOARD_IMAGE_CHAT_ROOT_ATTRIBUTE = "data-foundry-paste-eater-chat-root";
const CLIPBOARD_IMAGE_CHAT_UPLOAD_ACTION = "foundry-paste-eater-chat-upload";
const CLIPBOARD_IMAGE_TEXT_NOTE_FLAG = "textNote";
const CLIPBOARD_IMAGE_TEXT_NOTE_PAGE_NAME = "Notes";
const CLIPBOARD_IMAGE_TEXT_NOTE_JOURNAL_PREFIX = "Pasted Note";
const CLIPBOARD_IMAGE_VERBOSE_LOGGING_SETTING = "verbose-logging";
const CLIPBOARD_IMAGE_MINIMUM_ROLE_CANVAS_MEDIA_SETTING = "minimum-role-canvas-media";
const CLIPBOARD_IMAGE_MINIMUM_ROLE_CANVAS_TEXT_SETTING = "minimum-role-canvas-text";
const CLIPBOARD_IMAGE_MINIMUM_ROLE_CHAT_MEDIA_SETTING = "minimum-role-chat-media";
const CLIPBOARD_IMAGE_ALLOW_NON_GM_SCENE_CONTROLS_SETTING = "allow-non-gm-scene-controls";
const CLIPBOARD_IMAGE_ENABLE_CHAT_MEDIA_SETTING = "enable-chat-media";
const CLIPBOARD_IMAGE_ENABLE_CHAT_UPLOAD_BUTTON_SETTING = "enable-chat-upload-button";
const CLIPBOARD_IMAGE_ENABLE_TOKEN_CREATION_SETTING = "enable-token-creation";
const CLIPBOARD_IMAGE_ENABLE_TILE_CREATION_SETTING = "enable-tile-creation";
const CLIPBOARD_IMAGE_ENABLE_TOKEN_REPLACEMENT_SETTING = "enable-token-replacement";
const CLIPBOARD_IMAGE_ENABLE_TILE_REPLACEMENT_SETTING = "enable-tile-replacement";
const CLIPBOARD_IMAGE_ENABLE_SCENE_PASTE_TOOL_SETTING = "enable-scene-paste-tool";
const CLIPBOARD_IMAGE_ENABLE_SCENE_UPLOAD_TOOL_SETTING = "enable-scene-upload-tool";
const CLIPBOARD_IMAGE_DEFAULT_EMPTY_CANVAS_TARGET_SETTING = "default-empty-canvas-target";
const CLIPBOARD_IMAGE_CREATE_BACKING_ACTORS_SETTING = "create-backing-actors";
const CLIPBOARD_IMAGE_PASTED_TOKEN_ACTOR_TYPE_SETTING = "pasted-token-actor-type";
const CLIPBOARD_IMAGE_LOCK_PASTED_TOKEN_ROTATION_SETTING = "lock-pasted-token-rotation";
const CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_SETTING = "chat-media-display";
const CLIPBOARD_IMAGE_CANVAS_TEXT_PASTE_MODE_SETTING = "canvas-text-paste-mode";
const CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_SETTING = "scene-paste-prompt-mode";
const CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_SETTING = "selected-token-paste-mode";
const CLIPBOARD_IMAGE_UPLOAD_PATH_ORGANIZATION_SETTING = "upload-path-organization";
const CLIPBOARD_IMAGE_KNOWN_UPLOAD_ROOTS_SETTING = "known-upload-roots";
const CLIPBOARD_IMAGE_ROLE_PLAYER = "PLAYER";
const CLIPBOARD_IMAGE_ROLE_TRUSTED = "TRUSTED";
const CLIPBOARD_IMAGE_ROLE_ASSISTANT = "ASSISTANT";
const CLIPBOARD_IMAGE_ROLE_GAMEMASTER = "GAMEMASTER";
const CLIPBOARD_IMAGE_EMPTY_CANVAS_TARGET_ACTIVE_LAYER = "active-layer";
const CLIPBOARD_IMAGE_EMPTY_CANVAS_TARGET_TILE = "tile";
const CLIPBOARD_IMAGE_EMPTY_CANVAS_TARGET_TOKEN = "token";
const CLIPBOARD_IMAGE_PASTED_TOKEN_ACTOR_TYPE_ASK = "ask";
const CLIPBOARD_IMAGE_PASTED_TOKEN_ACTOR_TYPE_SYSTEM_DEFAULT = "system-default";
const CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_FULL_PREVIEW = "full-preview";
const CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_THUMBNAIL = "thumbnail";
const CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_LINK_ONLY = "link-only";
const CLIPBOARD_IMAGE_CANVAS_TEXT_PASTE_MODE_SCENE_NOTES = "scene-notes";
const CLIPBOARD_IMAGE_CANVAS_TEXT_PASTE_MODE_DISABLED = "disabled";
const CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_AUTO = "auto";
const CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_ALWAYS = "always";
const CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_NEVER = "never";
const CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_SCENE_ONLY = "scene-only";
const CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_ACTOR_ART = "actor-art";
const CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_PROMPT = "prompt";
const CLIPBOARD_IMAGE_UPLOAD_PATH_ORGANIZATION_FLAT = "flat";
const CLIPBOARD_IMAGE_UPLOAD_PATH_ORGANIZATION_CONTEXT_USER_MONTH = "context-user-month";
const CLIPBOARD_IMAGE_UPLOAD_CONTEXT_CANVAS = "canvas";
const CLIPBOARD_IMAGE_UPLOAD_CONTEXT_CHAT = "chat";
const CLIPBOARD_IMAGE_UPLOAD_CONTEXT_DOCUMENT_ART = "document-art";
const CLIPBOARD_IMAGE_UPLOAD_CONTEXT_PDF = "pdf";
const CLIPBOARD_IMAGE_UPLOAD_CONTEXT_AUDIO = "audio";
const CLIPBOARD_IMAGE_MEDIA_FILE_ACCEPT = "image/*,video/*,application/pdf,audio/*,.pdf,.aac,.flac,.m4a,.mid,.midi,.mp3,.ogg,.opus,.wav,.webm";
const CLIPBOARD_IMAGE_IMAGE_EXTENSIONS = new Set(["apng", "avif", "bmp", "gif", "ico", "jpeg", "jpg", "png", "svg", "tif", "tiff", "webp"]);
const CLIPBOARD_IMAGE_VIDEO_EXTENSIONS = new Set(["m4v", "mp4", "mpeg", "mpg", "ogv", "webm"]);
const CLIPBOARD_IMAGE_AUDIO_EXTENSIONS = new Set(["aac", "flac", "m4a", "mid", "midi", "mp3", "ogg", "opus", "wav", "webm"]);
const CLIPBOARD_IMAGE_SCENE_ACTION_CONTEXT_OPTIONS = Object.freeze({
  fallbackToCenter: true,
  requireCanvasFocus: false,
});

module.exports = {
  CLIPBOARD_IMAGE_MODULE_ID,
  CLIPBOARD_IMAGE_LEGACY_MODULE_ID,
  CLIPBOARD_IMAGE_TITLE,
  CLIPBOARD_IMAGE_DEFAULT_FOLDER,
  CLIPBOARD_IMAGE_SOURCE_AUTO,
  CLIPBOARD_IMAGE_SOURCE_DATA,
  CLIPBOARD_IMAGE_SOURCE_S3,
  CLIPBOARD_IMAGE_SOURCE_FORGE,
  CLIPBOARD_IMAGE_FILE_PICKER,
  CLIPBOARD_IMAGE_KEYBOARD_MANAGER,
  CLIPBOARD_IMAGE_FORM_APPLICATION,
  CLIPBOARD_IMAGE_SCENE_CONTROLS,
  CLIPBOARD_IMAGE_TOOL_PASTE,
  CLIPBOARD_IMAGE_TOOL_UPLOAD,
  CLIPBOARD_IMAGE_CHAT_ROOT_ATTRIBUTE,
  CLIPBOARD_IMAGE_CHAT_UPLOAD_ACTION,
  CLIPBOARD_IMAGE_TEXT_NOTE_FLAG,
  CLIPBOARD_IMAGE_TEXT_NOTE_PAGE_NAME,
  CLIPBOARD_IMAGE_TEXT_NOTE_JOURNAL_PREFIX,
  CLIPBOARD_IMAGE_VERBOSE_LOGGING_SETTING,
  CLIPBOARD_IMAGE_MINIMUM_ROLE_CANVAS_MEDIA_SETTING,
  CLIPBOARD_IMAGE_MINIMUM_ROLE_CANVAS_TEXT_SETTING,
  CLIPBOARD_IMAGE_MINIMUM_ROLE_CHAT_MEDIA_SETTING,
  CLIPBOARD_IMAGE_ALLOW_NON_GM_SCENE_CONTROLS_SETTING,
  CLIPBOARD_IMAGE_ENABLE_CHAT_MEDIA_SETTING,
  CLIPBOARD_IMAGE_ENABLE_CHAT_UPLOAD_BUTTON_SETTING,
  CLIPBOARD_IMAGE_ENABLE_TOKEN_CREATION_SETTING,
  CLIPBOARD_IMAGE_ENABLE_TILE_CREATION_SETTING,
  CLIPBOARD_IMAGE_ENABLE_TOKEN_REPLACEMENT_SETTING,
  CLIPBOARD_IMAGE_ENABLE_TILE_REPLACEMENT_SETTING,
  CLIPBOARD_IMAGE_ENABLE_SCENE_PASTE_TOOL_SETTING,
  CLIPBOARD_IMAGE_ENABLE_SCENE_UPLOAD_TOOL_SETTING,
  CLIPBOARD_IMAGE_DEFAULT_EMPTY_CANVAS_TARGET_SETTING,
  CLIPBOARD_IMAGE_CREATE_BACKING_ACTORS_SETTING,
  CLIPBOARD_IMAGE_PASTED_TOKEN_ACTOR_TYPE_SETTING,
  CLIPBOARD_IMAGE_LOCK_PASTED_TOKEN_ROTATION_SETTING,
  CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_SETTING,
  CLIPBOARD_IMAGE_CANVAS_TEXT_PASTE_MODE_SETTING,
  CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_SETTING,
  CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_SETTING,
  CLIPBOARD_IMAGE_UPLOAD_PATH_ORGANIZATION_SETTING,
  CLIPBOARD_IMAGE_KNOWN_UPLOAD_ROOTS_SETTING,
  CLIPBOARD_IMAGE_ROLE_PLAYER,
  CLIPBOARD_IMAGE_ROLE_TRUSTED,
  CLIPBOARD_IMAGE_ROLE_ASSISTANT,
  CLIPBOARD_IMAGE_ROLE_GAMEMASTER,
  CLIPBOARD_IMAGE_EMPTY_CANVAS_TARGET_ACTIVE_LAYER,
  CLIPBOARD_IMAGE_EMPTY_CANVAS_TARGET_TILE,
  CLIPBOARD_IMAGE_EMPTY_CANVAS_TARGET_TOKEN,
  CLIPBOARD_IMAGE_PASTED_TOKEN_ACTOR_TYPE_ASK,
  CLIPBOARD_IMAGE_PASTED_TOKEN_ACTOR_TYPE_SYSTEM_DEFAULT,
  CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_FULL_PREVIEW,
  CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_THUMBNAIL,
  CLIPBOARD_IMAGE_CHAT_MEDIA_DISPLAY_LINK_ONLY,
  CLIPBOARD_IMAGE_CANVAS_TEXT_PASTE_MODE_SCENE_NOTES,
  CLIPBOARD_IMAGE_CANVAS_TEXT_PASTE_MODE_DISABLED,
  CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_AUTO,
  CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_ALWAYS,
  CLIPBOARD_IMAGE_SCENE_PASTE_PROMPT_MODE_NEVER,
  CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_SCENE_ONLY,
  CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_ACTOR_ART,
  CLIPBOARD_IMAGE_SELECTED_TOKEN_PASTE_MODE_PROMPT,
  CLIPBOARD_IMAGE_UPLOAD_PATH_ORGANIZATION_FLAT,
  CLIPBOARD_IMAGE_UPLOAD_PATH_ORGANIZATION_CONTEXT_USER_MONTH,
  CLIPBOARD_IMAGE_UPLOAD_CONTEXT_CANVAS,
  CLIPBOARD_IMAGE_UPLOAD_CONTEXT_CHAT,
  CLIPBOARD_IMAGE_UPLOAD_CONTEXT_DOCUMENT_ART,
  CLIPBOARD_IMAGE_UPLOAD_CONTEXT_PDF,
  CLIPBOARD_IMAGE_UPLOAD_CONTEXT_AUDIO,
  CLIPBOARD_IMAGE_MEDIA_FILE_ACCEPT,
  CLIPBOARD_IMAGE_IMAGE_EXTENSIONS,
  CLIPBOARD_IMAGE_VIDEO_EXTENSIONS,
  CLIPBOARD_IMAGE_AUDIO_EXTENSIONS,
  CLIPBOARD_IMAGE_SCENE_ACTION_CONTEXT_OPTIONS,
};
