const CLIPBOARD_IMAGE_MODULE_ID = "clipboard-image";
const CLIPBOARD_IMAGE_DEFAULT_FOLDER = "pasted_images";
const CLIPBOARD_IMAGE_SOURCE_AUTO = "auto";
const CLIPBOARD_IMAGE_SOURCE_DATA = "data";
const CLIPBOARD_IMAGE_SOURCE_S3 = "s3";
const CLIPBOARD_IMAGE_SOURCE_FORGE = "forgevtt";
const CLIPBOARD_IMAGE_FILE_PICKER = foundry.applications.apps.FilePicker.implementation;
const CLIPBOARD_IMAGE_KEYBOARD_MANAGER = foundry.helpers.interaction.KeyboardManager;
const CLIPBOARD_IMAGE_FORM_APPLICATION = foundry.appv1.api.FormApplication;
const CLIPBOARD_IMAGE_SCENE_CONTROLS = ["tiles", "tokens"];
const CLIPBOARD_IMAGE_TOOL_PASTE = "clipboard-image-paste";
const CLIPBOARD_IMAGE_TOOL_UPLOAD = "clipboard-image-upload";
const CLIPBOARD_IMAGE_CHAT_ROOT_ATTRIBUTE = "data-clipboard-image-chat-root";
const CLIPBOARD_IMAGE_CHAT_UPLOAD_ACTION = "clipboard-image-chat-upload";
const CLIPBOARD_IMAGE_TEXT_NOTE_FLAG = "textNote";
const CLIPBOARD_IMAGE_TEXT_NOTE_PAGE_NAME = "Notes";
const CLIPBOARD_IMAGE_TEXT_NOTE_JOURNAL_PREFIX = "Pasted Note";
const CLIPBOARD_IMAGE_VERBOSE_LOGGING_SETTING = "verbose-logging";
const CLIPBOARD_IMAGE_MEDIA_FILE_ACCEPT = "image/*,video/*";
const CLIPBOARD_IMAGE_IMAGE_EXTENSIONS = new Set(["apng", "avif", "bmp", "gif", "ico", "jpeg", "jpg", "png", "svg", "tif", "tiff", "webp"]);
const CLIPBOARD_IMAGE_VIDEO_EXTENSIONS = new Set(["m4v", "mp4", "mpeg", "mpg", "ogg", "ogv", "webm"]);
const CLIPBOARD_IMAGE_SCENE_ACTION_CONTEXT_OPTIONS = Object.freeze({
  fallbackToCenter: true,
  requireCanvasFocus: false,
});

module.exports = {
  CLIPBOARD_IMAGE_MODULE_ID,
  CLIPBOARD_IMAGE_DEFAULT_FOLDER,
  CLIPBOARD_IMAGE_SOURCE_AUTO,
  CLIPBOARD_IMAGE_SOURCE_DATA,
  CLIPBOARD_IMAGE_SOURCE_S3,
  CLIPBOARD_IMAGE_SOURCE_FORGE,
  CLIPBOARD_IMAGE_FILE_PICKER,
  CLIPBOARD_IMAGE_KEYBOARD_MANAGER,
  CLIPBOARD_IMAGE_FORM_APPLICATION,
  CLIPBOARD_IMAGE_SCENE_CONTROLS,
  CLIPBOARD_IMAGE_TOOL_PASTE,
  CLIPBOARD_IMAGE_TOOL_UPLOAD,
  CLIPBOARD_IMAGE_CHAT_ROOT_ATTRIBUTE,
  CLIPBOARD_IMAGE_CHAT_UPLOAD_ACTION,
  CLIPBOARD_IMAGE_TEXT_NOTE_FLAG,
  CLIPBOARD_IMAGE_TEXT_NOTE_PAGE_NAME,
  CLIPBOARD_IMAGE_TEXT_NOTE_JOURNAL_PREFIX,
  CLIPBOARD_IMAGE_VERBOSE_LOGGING_SETTING,
  CLIPBOARD_IMAGE_MEDIA_FILE_ACCEPT,
  CLIPBOARD_IMAGE_IMAGE_EXTENSIONS,
  CLIPBOARD_IMAGE_VIDEO_EXTENSIONS,
  CLIPBOARD_IMAGE_SCENE_ACTION_CONTEXT_OPTIONS,
};
